# Generated by Django 4.0.5 on 2022-06-20 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='release_data',
            new_name='release_date',
        ),
    ]
